s = "GCTCGGGTGAAGGGGTGATCGCACGTCTACTTCTGTTCGTCTTTTGTCTACTGCCATAGAGCGTTTGCTTAATGAATGCTCACAGTGTGATTCCAGTGCGCTCGACGCACACTGACGGCGTGTAAAGGCGGGTCATACTCCGTATCTGAAGTAATCCTAGCAGCTAGTATACACTAAGTCGAAGGGGTCGACTTCAATACGTGCGCTCCACTCGGACGTAGAATGCATGGGCTGTTTCGCCCAACTAGGACGGCGGTCATCCGACCAGACAGGTATTTCATAGTATGGTGCCCTCCTAAGCAGCGTGTTAATGCTCCATGCGTTATTCCTAGTTTCCCGTATTTTAACCAATATGAGGCCGCAAGTAATGCAAGTTGCTAGGTAGGCGATATTAAAGGCTGAGCGTCGGGTCAACAGTCCGTATACTCCGATGCTAGTTCACTAGCGGGAGGGTTGGGATGGCAGACGATTATCAGAGTGCTCCCTCGCTCGCATGCACAGGGCGAGCACTGATGGAGCGAGTAGGCGGGAAAGGTGCTAAGTGAGAATCCAGCGGACTATCTAATAGGGCGACCCCGTCTCGGTGCGGAGGTACGCGTCTAAATGAACCTCGGGTACCAACGTCCCCCCGGTGGCTTGGCCTCACAAAACCTAACGGCGGTCTAAGAACCCTAAGAGTTCCAGGTAGTTGCTCCGCTACTGGCTGCAAATATCACGGACTAACAGGTCAGAACAGAGACGGGCTCTTTAACGGGGCTCAAAGCACCAGATTTATTCGAGCCTTATTCCGTTTAGTCGACGGCCAACCGCCGCGCAATAGGCGGGGACAACCCGTCCACGCACGCGGATATTACAGGTCAAGTAA"
count_A = 0
for letter in s:
    if letter == "A":
        count_A = count_A + 1

count_T = 0
for letter in s:
    if letter == "T":
        count_T = count_T + 1

count_G = 0
for letter in s:
    if letter == "G":
        count_G = count_G + 1

count_C = 0
for letter in s:
    if letter == "C":
        count_C = count_C + 1

print(count_A, count_C, count_G, count_T)